import type { Metadata } from 'next'
import Link from 'next/link'

export const metadata: Metadata = {
  title: 'Terms of Service',
  robots: { index: true, follow: true },
}

export default function Terms() {
  const updated = '1 July 2026'

  return (
    <main className="min-h-dvh bg-[#080810] text-white px-6 py-16">
      <div className="max-w-[680px] mx-auto">
        <Link href="/" className="text-[11px] font-bold tracking-[0.2em] text-yellow-400/70 uppercase hover:text-yellow-400 transition-colors">
          ← Demist
        </Link>

        <h1 className="text-[34px] font-bold tracking-tight mt-8 mb-2">Terms of Service</h1>
        <p className="text-gray-600 text-[14px] mb-12">Last updated {updated}</p>

        <div className="space-y-10 text-[15px] leading-relaxed">

          <section>
            <h2 className="text-[17px] font-semibold mb-3">About Demist</h2>
            <p className="text-gray-400">
              Demist is a study tool that helps university students understand lecture terminology in real time. It is provided as-is to support personal learning. By using Demist, you agree to these terms.
            </p>
          </section>

          <section>
            <h2 className="text-[17px] font-semibold mb-3">Acceptable use</h2>
            <p className="text-gray-400">
              Demist is for your personal study only. You are responsible for ensuring you have any permissions required to record or process lectures at your institution — in particular, written consent from lecturers before saving transcripts in microphone mode. Do not use Demist to redistribute others&apos; lecture content publicly or in any way that infringes copyright or performers&apos; rights.
            </p>
          </section>

          <section>
            <h2 className="text-[17px] font-semibold mb-3">AI-generated content &amp; no professional advice</h2>
            <p className="text-gray-400">
              Term definitions and summaries are generated by AI and may occasionally be inaccurate, incomplete, or misleading. They are not professional, medical, legal, or academic advice. Always verify anything important against your course materials, textbooks, or a qualified professional.
            </p>
          </section>

          <section>
            <h2 className="text-[17px] font-semibold mb-3">Limitation of liability</h2>
            <p className="text-gray-400">
              To the fullest extent permitted by law, Demist and its creators are not liable for any loss or damage arising from your use of the service or reliance on AI-generated content. The service is provided without warranties of any kind, express or implied.
            </p>
          </section>

          <section>
            <h2 className="text-[17px] font-semibold mb-3">Accounts &amp; termination</h2>
            <p className="text-gray-400">
              You may delete your account at any time from your profile settings. We may suspend or terminate accounts that misuse the service, abuse our systems, or violate these terms.
            </p>
          </section>

          <section>
            <h2 className="text-[17px] font-semibold mb-3">Changes to these terms</h2>
            <p className="text-gray-400">
              We may update these terms from time to time. We&apos;ll update the date at the top of this page when we do. Continued use of Demist after a change means you accept the updated terms.
            </p>
          </section>

          <section>
            <h2 className="text-[17px] font-semibold mb-3">Contact</h2>
            <p className="text-gray-400">
              Questions about these terms: <a href="mailto:hello@demist.app" className="text-yellow-400 hover:text-yellow-300 transition-colors">hello@demist.app</a>
            </p>
          </section>

        </div>

        <div className="mt-16 pt-8 border-t border-white/[0.05]">
          <Link href="/" className="text-[13px] text-gray-600 hover:text-gray-400 transition-colors">
            ← Back to Demist
          </Link>
        </div>
      </div>
    </main>
  )
}
